Update changelog and version for v0.2.0
bottlerocket-os/twoliter pull request #247
Opened 2024-05-29 23:12 UTC by sumukhballal

**Issue number:**

Closes #

**Description of changes:**

Updates twoliter to v0.2.0.

**Testing done:**

-[ ] Build a bottlerocket variant and it works as is.

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

2024-05-30 16:28 UTC, webern reviewed
You will need to run `cargo check` or `cargo build` to update `Cargo.lock` in the same commit where you bump the version in Twoliter's Cargo.toml. CI checks fail if the Cargo.lock file is not up-to-date.

You should also do a commit where you update dependencies with `cargo update`.

Thanks!

2024-05-30 16:28 UTC, webern commented on CHANGELOG.md
> +- Added a Buildsys build kit command ([#227])
```suggestion
- Added the buildsys build-kit command to create kits ([#198], [#227])
```

2024-05-30 16:28 UTC, webern commented on CHANGELOG.md
> +- Added a dependency graph algorithm for package and kit builds ([#198])
```suggestion
```

2024-05-30 16:28 UTC, webern commented on CHANGELOG.md
> +- Remove variant sensitivity from buildsys ([#220])
```suggestion
- Deprecate variant sensitivity for packages in buildsys ([#220])
```

2024-05-30 17:43 UTC, sumukhballal commented
Updated changelog to address @webern's concern.

2024-05-31 12:29 UTC, webern approved these changes

2024-05-31 15:04 UTC, jpculp requested changes

2024-05-31 15:04 UTC, jpculp commented on CHANGELOG.md
> +- Add support to repack a variant ([#214], [#211], [#217], [#219], [#221], [#222], [#228], [#231], [#235], [#236], [#243])
#236 is a tangential, but standalone feature. Let's add a new line for "Add support to fetch a variant"

2024-05-31 15:13 UTC, sumukhballal commented
Adding change to address @jpculp 's comment.

2024-05-31 15:53 UTC, jpculp approved these changes

2024-05-31 16:03 UTC, merged