Update changelog and version for v0.3.0
bottlerocket-os/twoliter pull request #289
Opened 2024-06-13 22:10 UTC by sumukhballal

**Issue number:**

Closes #

**Description of changes:**

Updates twoliter to v0.2.0.

**Testing done:**

- [ ] Add temporary commit which includes pre-release version.
- [ ] Build a bottlerocket variant and it works as is.
- [ ] Make sure Cargo.lock is updated.

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

2024-06-13 22:40 UTC, webern approved these changes

2024-06-13 22:42 UTC, webern requested changes
Marking this as blocked because we are going to need a PR (not open yet) from Sam to fix some kit publishing details.

2024-06-14 23:05 UTC, webern approved these changes

2024-06-14 23:08 UTC, sumukhballal commented
Updated with latest Twoliter version and with rebase.

2024-06-14 23:10 UTC, jmt-lab approved these changes
LGTM

2024-06-14 23:13 UTC, sam-berning approved these changes

2024-06-14 23:30 UTC, merged